services:
  # PHP-FPM 
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    container_name: app_php
    volumes:
      - storage:/var/www/html/storage
    command: sh -c "chmod -R 777 /var/www/html/storage && php vendor/bin/doctrine-migrations migrate --configuration config/migrations.php --db-configuration config/db_config.php -n && php-fpm"
    depends_on:
      db:
        condition: service_healthy
    networks:
      app-network:
        ipv4_address: 172.20.0.2

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: app_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html/src/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      app-network:
        ipv4_address: 172.20.0.3

  # MySQL 
  db:
    image: mysql:8.0.40
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app-network:
        ipv4_address: 172.20.0.4
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  storage:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24